server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri /index.html;
  }

  location /v1/ {
    proxy_pass http://api:8000;
  }
  location /health {
    proxy_pass http://api:8000;
  }
  location /ready {
    proxy_pass http://api:8000;
  }
  location /metrics {
    proxy_pass http://api:8000;
  }
}
