"""Node catalog required by the specification."""

from __future__ import annotations

NODE_CATALOG = {
    "plan": {
        "purpose": "Classify the question and produce specialist retrieval queries.",
        "input_schema": "PlannerInput",
        "output_schema": "ResearchPlan",
        "tools_used": [],
        "state_modified": ["plan"],
        "failure_states": ["VALIDATION_FAILED"],
        "timeout_seconds": 2,
        "retry_policy": "none",
        "observability": ["span:plan", "event:plan.completed"],
        "security": "Question is length-bounded and redacted in logs.",
    },
    "retrieve": {
        "purpose": "Hybrid retrieve + rerank filing chunks per specialist query.",
        "input_schema": "ResearchPlan",
        "output_schema": "list[RetrievedChunk]",
        "tools_used": ["retrieve_filings"],
        "state_modified": ["evidence"],
        "failure_states": ["TOOL_FAILURE", "INSUFFICIENT_EVIDENCE"],
        "timeout_seconds": 6,
        "retry_policy": "retry 2 with timeout wrapper",
        "observability": ["span:retrieve", "metric:retrieval_latency_ms"],
        "security": "Retrieved text is untrusted; never executed as instructions.",
    },
    "specialists": {
        "purpose": "Bull, Bear, Financial, Risk, and Evidence agents emit claims.",
        "input_schema": "SpecialistInput",
        "output_schema": "SpecialistBrief",
        "tools_used": ["retrieve_filings"],
        "state_modified": ["briefs"],
        "failure_states": ["PROVIDER_TIMEOUT", "VALIDATION_FAILED"],
        "timeout_seconds": 20,
        "retry_policy": "bounded structured-output repair",
        "observability": ["span:specialist", "metric:token_usage"],
        "security": "Role-specific query templates; no write tools.",
    },
    "normalize": {
        "purpose": "Canonicalize claims onto ticker.metric.period topic keys.",
        "input_schema": "NormalizeInput",
        "output_schema": "NormalizeOutput",
        "tools_used": [],
        "state_modified": ["claims"],
        "failure_states": ["VALIDATION_FAILED"],
        "timeout_seconds": 2,
        "retry_policy": "none",
        "observability": ["span:normalize"],
        "security": "Deterministic; no external I/O.",
    },
    "disagreement": {
        "purpose": "Build the disagreement matrix and count contradictions.",
        "input_schema": "DisagreementInput",
        "output_schema": "DisagreementOutput",
        "tools_used": [],
        "state_modified": ["disagreement", "unresolved"],
        "failure_states": ["VALIDATION_FAILED"],
        "timeout_seconds": 2,
        "retry_policy": "none",
        "observability": ["span:disagreement", "metric:contradiction_count"],
        "security": "Deterministic; no external I/O.",
    },
    "critic": {
        "purpose": "Attack unsupported assumptions, cherry-picking, and stale 8-Ks.",
        "input_schema": "CriticInput",
        "output_schema": "CriticOutput",
        "tools_used": [],
        "state_modified": ["critic_findings"],
        "failure_states": ["VALIDATION_FAILED"],
        "timeout_seconds": 3,
        "retry_policy": "none",
        "observability": ["span:critic"],
        "security": "Read-only over claims and briefs.",
    },
    "validate": {
        "purpose": "Check each claim against its citation span and numbers.",
        "input_schema": "ValidatorInput",
        "output_schema": "ValidatorOutput",
        "tools_used": [],
        "state_modified": ["validations", "claims"],
        "failure_states": ["VALIDATION_FAILED"],
        "timeout_seconds": 3,
        "retry_policy": "none",
        "observability": ["span:validate", "metric:unsupported_claim_rate"],
        "security": "Citations must resolve to indexed chunks.",
    },
    "resolve": {
        "purpose": "Re-rank conflicting claims by primary-evidence rules.",
        "input_schema": "DisagreementOutput",
        "output_schema": "updated claims + unresolved keys",
        "tools_used": ["retrieve_filings"],
        "state_modified": ["claims", "resolved", "unresolved"],
        "failure_states": ["INSUFFICIENT_EVIDENCE"],
        "timeout_seconds": 6,
        "retry_policy": "single extra retrieval",
        "observability": ["span:resolve"],
        "security": "Cannot invent values; may only prefer among cited facts.",
    },
    "synthesize": {
        "purpose": "Produce the final report without forcing consensus.",
        "input_schema": "SynthesizerInput",
        "output_schema": "SynthesisReport",
        "tools_used": [],
        "state_modified": ["report"],
        "failure_states": ["INSUFFICIENT_EVIDENCE", "UNRESOLVED"],
        "timeout_seconds": 4,
        "retry_policy": "none",
        "observability": ["span:synthesize"],
        "security": "Output citations only from retrieved evidence.",
    },
}
